language: node_js  
node_js:  
  - "10.17.0"  
cache:  
  directories:  
    - "node_modules"  
services:  
  - postgresql  
before_script:  
  - cp config/database.ci.js config/database.js  
  - psql -c 'create database mymoney_ci_test;' -U postgres
  # - docker-compose -f docker-compose.ci-test.yml up -d
script:  
  - npm run prettier:check  
  - npm run lint  
  - npm run test