version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: My Money by Adam
    env_file:
      - .env
    ports:
      - "3310:3310"
    volumes:
      - ./:/usr/src/app
